# Generated by Django 5.2.6 on 2025-09-21 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterials',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='unit',
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='myapp.product'),
        ),
    ]
