# Generated by Django 5.2.6 on 2025-09-20 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_workproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='component',
            name='available_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='component',
            name='unit',
            field=models.CharField(default='pcs', max_length=50),
        ),
    ]
