# Generated by Django 5.2.6 on 2025-09-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_billofmaterials_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='unit',
            field=models.CharField(default='Units', max_length=20),
        ),
    ]
