# Generated by Django 5.2.6 on 2025-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_component_product_alter_component_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='unit',
            field=models.CharField(choices=[('Units', 'Units'), ('Kg', 'Kilogram'), ('Litre', 'Litre'), ('Meter', 'Meter')], default='Units', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Units', 'Units'), ('Kg', 'Kilogram'), ('Litre', 'Litre'), ('Meter', 'Meter')], default='Units', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
