# Generated by Django 5.2.6 on 2025-09-21 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_billofmaterials_quantity_billofmaterials_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
