# Generated by Django 5.2.6 on 2025-09-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_manufacturingorder_unit_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='unit',
            field=models.CharField(choices=[('Units', 'Units'), ('Kg', 'Kilogram'), ('Litre', 'Litre'), ('Meter', 'Meter'), ('Pcs', 'Pieces')], default='Units', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Units', 'Units'), ('Kg', 'Kilogram'), ('Litre', 'Litre'), ('Meter', 'Meter'), ('Pcs', 'Pieces')], default='Units', max_length=20),
        ),
    ]
