# Generated by Django 5.2.6 on 2025-09-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_manufacturingorder_unit_alter_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='component',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manufacturingordercomponent',
            name='manufacturing_order',
        ),
        migrations.RemoveField(
            model_name='manufacturingordercomponent',
            name='to_consume',
        ),
        migrations.AddField(
            model_name='component',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='component',
            name='used_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manufacturingordercomponent',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
        migrations.CreateModel(
            name='BillofMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.billofmaterials'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_minutes', models.PositiveIntegerField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='myapp.billofmaterials')),
            ],
        ),
        migrations.DeleteModel(
            name='BillOfMaterial',
        ),
    ]
