# Generated by Django 5.2.6 on 2025-09-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_add_fields_to_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='bill_of_material',
        ),
        migrations.RemoveField(
            model_name='component',
            name='quantity',
        ),
    ]
